-- Secure the public data API and scope podcast progress to one Supabase user.
-- The frontend uses Supabase anonymous auth, so anonymous sign-ins must be
-- enabled in the project authentication settings.

-- ── Public reference data ───────────────────────────────────────────────────

alter table teams enable row level security;
alter table fixtures enable row level security;
alter table standings enable row level security;
alter table top_scorers enable row level security;
alter table news_items enable row level security;
alter table sync_log enable row level security;
alter table standings_snapshots enable row level security;
alter table match_stats enable row level security;
alter table leagues enable row level security;

drop policy if exists "public read teams" on teams;
create policy "public read teams" on teams
  for select to anon, authenticated using (true);

drop policy if exists "public read fixtures" on fixtures;
create policy "public read fixtures" on fixtures
  for select to anon, authenticated using (true);

drop policy if exists "public read standings" on standings;
create policy "public read standings" on standings
  for select to anon, authenticated using (true);

drop policy if exists "public read top scorers" on top_scorers;
create policy "public read top scorers" on top_scorers
  for select to anon, authenticated using (true);

drop policy if exists "public read news items" on news_items;
create policy "public read news items" on news_items
  for select to anon, authenticated using (true);

drop policy if exists "public read standings snapshots" on standings_snapshots;
create policy "public read standings snapshots" on standings_snapshots
  for select to anon, authenticated using (true);

drop policy if exists "public read match stats" on match_stats;
create policy "public read match stats" on match_stats
  for select to anon, authenticated using (true);

drop policy if exists "public read leagues" on leagues;
create policy "public read leagues" on leagues
  for select to anon, authenticated using (true);

-- sync_log deliberately has no public policy. Service-role jobs bypass RLS.
-- The other tables also have no public write policy, so only the service role
-- can synchronize provider data.

-- ── Viewer-owned podcast progress ───────────────────────────────────────────

alter table podcast_progress
  add column if not exists id bigint generated by default as identity;

alter table podcast_progress
  add column if not exists user_id uuid references auth.users(id) on delete cascade;

-- Preserve existing rows. They remain ownerless and inaccessible rather than
-- being assigned to the first viewer that happens to open the upgraded app.
alter table podcast_progress drop constraint if exists podcast_progress_pkey;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'podcast_progress'::regclass
      and conname = 'podcast_progress_id_pkey'
  ) then
    alter table podcast_progress
      add constraint podcast_progress_id_pkey primary key (id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'podcast_progress'::regclass
      and conname = 'podcast_progress_user_episode_key'
  ) then
    alter table podcast_progress
      add constraint podcast_progress_user_episode_key unique (user_id, episode_guid);
  end if;
end $$;

drop policy if exists "anon read" on podcast_progress;
drop policy if exists "anon write" on podcast_progress;
drop policy if exists "viewer read own progress" on podcast_progress;
drop policy if exists "viewer insert own progress" on podcast_progress;
drop policy if exists "viewer update own progress" on podcast_progress;
drop policy if exists "viewer delete own progress" on podcast_progress;

create policy "viewer read own progress" on podcast_progress
  for select to authenticated
  using (auth.uid() = user_id);

create policy "viewer insert own progress" on podcast_progress
  for insert to authenticated
  with check (auth.uid() = user_id);

create policy "viewer update own progress" on podcast_progress
  for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "viewer delete own progress" on podcast_progress
  for delete to authenticated
  using (auth.uid() = user_id);
